### PR TITLE
Fire event on child element when view status changes

### LINKED ISSUE #2: Expose px-view status to the child element
I'd like to be able to detect from within my element which has been added to px-view status changes from `shown` -> `hidden`.

This would enable be to, for example, stop an iron-ajax request when the view is hidden.

I can't see how I can currently achieve this with the existing px-view.

### PR DESCRIPTION
**Pull request by manderson23**
To fix #2 I've added an event that is fired on the child element when the view status changes.

### CODE REVIEW

**Comment by leebickmtu** [comment]
This is exactly what I need. Been doing a much hackier way of getting these events. But added these changes, and works perfect. Please merge.

**Comment by runn-vermel** [comment]
HI @manderson23 

This looks great - normally, we ask for tests to accompany PRs, but since there aren't any real tests written for this anyway, we aren't going to require tests (unless you want to write some!).

One small change request - can you please rename the event name from view-status-changed to px-view-status-changed - we try to pre-face the event with the component name.

Let me know when that change is done and i'll be happy to merge this in.

**Comment by manderson23** [comment]
@runn-vermel no problem. I'll make the changes when I'm back at work.

I did think about tests but when I looked at what already existed it didn't seem to do much so I left it.

**Comment by manderson23** [comment]
@runn-vermel changes made.

**Comment by runn-vermel** [comment]
Hi @manderson23 

Thanks again for the PR, it should be available in version v1.1.0.

**Pull request merged**
